language: node_js
node_js:
  - "8"
install:
  # Use npm 5.7.x since it has introduced `npm ci`
  - if [[ `npm -v` != 5.7* ]]; then npm install -g npm@'>=5.7.1'; fi
  - npm ci
branches:
  except:
    - gh-pages
stages:
  - lint
  - test
  - build
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - yarn lint
    - stage: test
      script:
        # Run tests
        - yarn test
    - stage: build
      script:
        # Build all
        - yarn build:docs
        - yarn build:system
        - yarn build:app
